# Generated by Django 3.2.4 on 2021-08-18 11:15

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportCorpusTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('description', models.CharField(blank=True, max_length=256, verbose_name='description')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('started_on', models.DateTimeField(null=True, verbose_name='started on')),
                ('completed_on', models.DateTimeField(null=True, verbose_name='completed on')),
                ('progress', models.IntegerField(blank=True, null=True, verbose_name='progress')),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('RECEIVED', 'RECEIVED'), ('STARTED', 'STARTED'), ('PROGESS', 'PROGESS'), ('SUCCESS', 'SUCCESS'), ('FAILURE', 'FAILURE'), ('REVOKED', 'REVOKED'), ('REJECTED', 'REJECTED'), ('RETRY', 'RETRY'), ('IGNORED', 'IGNORED')], db_index=True, default='PENDING', max_length=128, verbose_name='status')),
                ('job_id', models.CharField(blank=True, max_length=128, verbose_name='job id')),
                ('mode', models.CharField(choices=[('UNKNOWN', 'UNKNOWN'), ('SYNC', 'SYNC'), ('ASYNC', 'ASYNC')], db_index=True, default='UNKNOWN', max_length=128, verbose_name='mode')),
                ('failure_reason', models.CharField(blank=True, max_length=256, verbose_name='failure reason')),
                ('log_text', models.TextField(blank=True, verbose_name='log text')),
                ('file_format', models.CharField(choices=[('txt', 'Text File')], default='txt', max_length=5)),
                ('file_compression', models.CharField(choices=[('none', 'No compressiong'), ('bz2', 'Bzip2')], default='none', max_length=5)),
                ('corpora', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('news', 'News and magazines'), ('wiki', 'Ukrainian Wikipedia'), ('fiction', 'Fiction'), ('court', 'Sampled court decisions'), ('laws', 'Laws and bylaws')], max_length=10), size=None)),
                ('filtering', models.CharField(choices=[('none', 'No filtering applied')], max_length=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_on',),
                'get_latest_by': 'created_on',
                'abstract': False,
            },
        ),
    ]
