# Generated by Django 3.2.4 on 2021-08-18 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportcorpustask',
            name='processing',
            field=models.CharField(choices=[('orig', 'Original texts in markdown format'), ('tokens', 'Tokenized by NLP-UK lib'), ('lemmas', 'Lemmatized by NLP-UK lib')], default='orig', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exportcorpustask',
            name='file_compression',
            field=models.CharField(choices=[('none', 'No compression'), ('bz2', 'Bzip2')], default='none', max_length=5),
        ),
    ]
