# Generated by Django 3.2.8 on 2021-10-06 20:44

import corpus.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0003_auto_20211005_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportcorpustask',
            name='corpora',
            field=corpus.models.ChoiceArrayField(base_field=models.CharField(choices=[('news', 'News and magazines'), ('wikipedia', 'Ukrainian Wikipedia'), ('fiction', 'Fiction'), ('court', 'Sampled court decisions'), ('laws', 'Laws and bylaws')], max_length=10), size=None),
        ),
    ]
