# Generated by Django 3.2.8 on 2022-01-25 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0005_tagwithudpipetask'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagwithudpipetask',
            name='force',
            field=models.BooleanField(default=False, verbose_name='Tag all texts, including already tagged'),
        ),
    ]
