# Generated by Django 3.2.12 on 2022-06-28 15:59

import corpus.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0008_auto_20220207_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildfreqvocabtask',
            name='filtering',
            field=corpus.models.ChoiceArrayField(base_field=models.CharField(choices=[('rus', 'Filter out texts with a lot of russian words'), ('short', 'Filter out texts, where title and body combined are too short')], max_length=10), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='exportcorpustask',
            name='processing',
            field=models.CharField(choices=[('orig', 'Original texts in markdown format'), ('orig_titles', 'Original titles'), ('tokens', 'Tokenized by NLP-UK lib'), ('lemmas', 'Lemmatized by NLP-UK lib')], max_length=15),
        ),
    ]
