# Generated by Django 4.1.8 on 2026-07-05 05:32

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("taggit", "0005_auto_20220424_2025"),
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArtifactPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        default="", max_length=255, verbose_name="[EN] Назва сторінки"
                    ),
                ),
                (
                    "global_class",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="CSS-Клас сторінки",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.RichTextField(
                        blank=True,
                        default="",
                        verbose_name="[UA] Загальний текст сторінки",
                    ),
                ),
                (
                    "body_en",
                    wagtail.fields.RichTextField(
                        blank=True,
                        default="",
                        verbose_name="[EN] Загальний текст сторінки",
                    ),
                ),
                (
                    "svg_image",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Content of the SVG tag, ignored if empty",
                        verbose_name="SVG image icon (raw text) to display next to menu item",
                    ),
                ),
                (
                    "short_description",
                    models.TextField(
                        blank=True,
                        default="",
                        verbose_name="Короткий опис (для картки)",
                    ),
                ),
                (
                    "short_description_en",
                    models.TextField(
                        blank=True,
                        default="",
                        verbose_name="[EN] Короткий опис (для картки)",
                    ),
                ),
                (
                    "authors",
                    models.CharField(
                        blank=True, default="", max_length=512, verbose_name="Автори"
                    ),
                ),
                (
                    "license",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="Ліцензія"
                    ),
                ),
                (
                    "stats",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Обсяг/статистика (вільний текст)",
                    ),
                ),
                (
                    "last_significant_update",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Дата останнього суттєвого оновлення",
                    ),
                ),
            ],
            options={
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукти",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="ArtifactType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Назва типу")),
                (
                    "name_en",
                    models.CharField(max_length=255, verbose_name="[EN] Назва типу"),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="Слаг")),
                (
                    "svg_image",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Content of the SVG tag, ignored if empty",
                        verbose_name="SVG image icon (raw text)",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Порядок сортування"
                    ),
                ),
            ],
            options={
                "verbose_name": "Тип продукту",
                "verbose_name_plural": "Типи продуктів",
                "ordering": ("sort_order", "name"),
            },
        ),
        migrations.CreateModel(
            name="SectionPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        default="", max_length=255, verbose_name="[EN] Назва сторінки"
                    ),
                ),
                (
                    "global_class",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="CSS-Клас сторінки",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.RichTextField(
                        blank=True,
                        default="",
                        verbose_name="[UA] Загальний текст сторінки",
                    ),
                ),
                (
                    "body_en",
                    wagtail.fields.RichTextField(
                        blank=True,
                        default="",
                        verbose_name="[EN] Загальний текст сторінки",
                    ),
                ),
                (
                    "svg_image",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Content of the SVG tag, ignored if empty",
                        verbose_name="SVG image icon (raw text) to display next to menu item",
                    ),
                ),
                (
                    "artifact_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sections",
                        to="catalog.artifacttype",
                        verbose_name="Тип продукту",
                    ),
                ),
            ],
            options={
                "verbose_name": "Розділ каталогу",
                "verbose_name_plural": "Розділи каталогу",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="ArtifactPageTag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_object",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tagged_items",
                        to="catalog.artifactpage",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_items",
                        to="taggit.tag",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="artifactpage",
            name="artifact_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="artifacts",
                to="catalog.artifacttype",
                verbose_name="Тип продукту",
            ),
        ),
        migrations.AddField(
            model_name="artifactpage",
            name="tags",
            field=modelcluster.contrib.taggit.ClusterTaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="catalog.ArtifactPageTag",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AddField(
            model_name="artifactpage",
            name="thumbnail",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Мініатюра",
            ),
        ),
        migrations.CreateModel(
            name="ArtifactLink",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("github", "GitHub"),
                            ("huggingface", "Hugging Face"),
                            ("paper", "Наукова праця"),
                            ("demo", "Демо"),
                            ("download", "Завантаження"),
                            ("docs", "Документація"),
                            ("other", "Інше"),
                        ],
                        default="download",
                        max_length=20,
                        verbose_name="Тип посилання",
                    ),
                ),
                ("url", models.URLField(verbose_name="Посилання")),
                (
                    "caption",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Підпис (опційно)",
                    ),
                ),
                (
                    "caption_en",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="[EN] Підпис (опційно)",
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="catalog.artifactpage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
