# Generated by Django 4.1.8 on 2026-07-05 07:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_seed_artifact_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artifactpage",
            name="title_en",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="[EN] Назва сторінки",
            ),
        ),
        migrations.AlterField(
            model_name="sectionpage",
            name="title_en",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="[EN] Назва сторінки",
            ),
        ),
    ]
