# Generated by Django 4.1.8 on 2026-07-05 07:23

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
        ("catalog", "0003_alter_artifactpage_title_en_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedbackPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="[EN] Назва сторінки",
                    ),
                ),
                (
                    "global_class",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="CSS-Клас сторінки",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.RichTextField(
                        blank=True,
                        default="",
                        verbose_name="[UA] Загальний текст сторінки",
                    ),
                ),
                (
                    "body_en",
                    wagtail.fields.RichTextField(
                        blank=True,
                        default="",
                        verbose_name="[EN] Загальний текст сторінки",
                    ),
                ),
                (
                    "svg_image",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Content of the SVG tag, ignored if empty",
                        verbose_name="SVG image icon (raw text) to display next to menu item",
                    ),
                ),
                (
                    "thank_you_caption",
                    wagtail.fields.RichTextField(
                        default="", verbose_name="Подяка за повідомлення"
                    ),
                ),
                (
                    "thank_you_caption_en",
                    wagtail.fields.RichTextField(
                        default="", verbose_name="[EN] Подяка за повідомлення"
                    ),
                ),
                (
                    "thank_you_text",
                    wagtail.fields.RichTextField(
                        default="", verbose_name="Текст подяки за повідомлення"
                    ),
                ),
                (
                    "thank_you_text_en",
                    wagtail.fields.RichTextField(
                        default="", verbose_name="[EN] Текст подяки за повідомлення"
                    ),
                ),
            ],
            options={
                "verbose_name": "Сторінка відгуків про використання",
            },
            bases=("wagtailcore.page", models.Model),
        ),
        migrations.CreateModel(
            name="SubmitArtifactPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="[EN] Назва сторінки",
                    ),
                ),
                (
                    "global_class",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="CSS-Клас сторінки",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.RichTextField(
                        blank=True,
                        default="",
                        verbose_name="[UA] Загальний текст сторінки",
                    ),
                ),
                (
                    "body_en",
                    wagtail.fields.RichTextField(
                        blank=True,
                        default="",
                        verbose_name="[EN] Загальний текст сторінки",
                    ),
                ),
                (
                    "svg_image",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Content of the SVG tag, ignored if empty",
                        verbose_name="SVG image icon (raw text) to display next to menu item",
                    ),
                ),
                (
                    "thank_you_caption",
                    wagtail.fields.RichTextField(
                        default="", verbose_name="Подяка за повідомлення"
                    ),
                ),
                (
                    "thank_you_caption_en",
                    wagtail.fields.RichTextField(
                        default="", verbose_name="[EN] Подяка за повідомлення"
                    ),
                ),
                (
                    "thank_you_text",
                    wagtail.fields.RichTextField(
                        default="", verbose_name="Текст подяки за повідомлення"
                    ),
                ),
                (
                    "thank_you_text_en",
                    wagtail.fields.RichTextField(
                        default="", verbose_name="[EN] Текст подяки за повідомлення"
                    ),
                ),
            ],
            options={
                "verbose_name": "Сторінка додавання продукту",
            },
            bases=("wagtailcore.page", models.Model),
        ),
        migrations.CreateModel(
            name="UsageFeedback",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(
                        blank=True,
                        help_text="Якщо продукту немає у списку",
                        max_length=255,
                        verbose_name="Продукт (як текст)",
                    ),
                ),
                ("how_used", models.TextField(verbose_name="Як і де використовується")),
                (
                    "organization",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Організація/проєкт"
                    ),
                ),
                (
                    "submitter_name",
                    models.CharField(max_length=255, verbose_name="Ваше ім'я"),
                ),
                (
                    "submitter_email",
                    models.EmailField(max_length=254, verbose_name="Ваш e-mail"),
                ),
                (
                    "added",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Був надісланий"
                    ),
                ),
                (
                    "artifact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feedback",
                        to="catalog.artifactpage",
                        verbose_name="Продукт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Відгук про використання",
                "verbose_name_plural": "Відгуки про використання",
                "ordering": ("-added",),
            },
        ),
        migrations.CreateModel(
            name="ArtifactSubmission",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Назва продукту"),
                ),
                ("description", models.TextField(verbose_name="Опис")),
                (
                    "links",
                    models.TextField(
                        blank=True,
                        help_text="По одному посиланню в рядку",
                        verbose_name="Посилання",
                    ),
                ),
                (
                    "license",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Ліцензія"
                    ),
                ),
                (
                    "authors",
                    models.CharField(blank=True, max_length=512, verbose_name="Автори"),
                ),
                (
                    "submitter_name",
                    models.CharField(max_length=255, verbose_name="Ваше ім'я"),
                ),
                (
                    "submitter_email",
                    models.EmailField(max_length=254, verbose_name="Ваш e-mail"),
                ),
                (
                    "added",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Був надісланий"
                    ),
                ),
                (
                    "processed",
                    models.BooleanField(default=False, verbose_name="Опрацьовано"),
                ),
                (
                    "artifact_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submissions",
                        to="catalog.artifacttype",
                        verbose_name="Тип продукту",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка на додавання продукту",
                "verbose_name_plural": "Заявки на додавання продуктів",
                "ordering": ("-added",),
            },
        ),
    ]
