# Generated by Django 4.1.8 on 2026-07-05 17:27

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0005_populate_community_artifacts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedbackpage",
            name="thank_you_caption",
            field=wagtail.fields.RichTextField(
                blank=True, default="", verbose_name="Подяка за повідомлення"
            ),
        ),
        migrations.AlterField(
            model_name="feedbackpage",
            name="thank_you_caption_en",
            field=wagtail.fields.RichTextField(
                blank=True, default="", verbose_name="[EN] Подяка за повідомлення"
            ),
        ),
        migrations.AlterField(
            model_name="feedbackpage",
            name="thank_you_text",
            field=wagtail.fields.RichTextField(
                blank=True, default="", verbose_name="Текст подяки за повідомлення"
            ),
        ),
        migrations.AlterField(
            model_name="feedbackpage",
            name="thank_you_text_en",
            field=wagtail.fields.RichTextField(
                blank=True, default="", verbose_name="[EN] Текст подяки за повідомлення"
            ),
        ),
        migrations.AlterField(
            model_name="submitartifactpage",
            name="thank_you_caption",
            field=wagtail.fields.RichTextField(
                blank=True, default="", verbose_name="Подяка за повідомлення"
            ),
        ),
        migrations.AlterField(
            model_name="submitartifactpage",
            name="thank_you_caption_en",
            field=wagtail.fields.RichTextField(
                blank=True, default="", verbose_name="[EN] Подяка за повідомлення"
            ),
        ),
        migrations.AlterField(
            model_name="submitartifactpage",
            name="thank_you_text",
            field=wagtail.fields.RichTextField(
                blank=True, default="", verbose_name="Текст подяки за повідомлення"
            ),
        ),
        migrations.AlterField(
            model_name="submitartifactpage",
            name="thank_you_text_en",
            field=wagtail.fields.RichTextField(
                blank=True, default="", verbose_name="[EN] Текст подяки за повідомлення"
            ),
        ),
    ]
