# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 23:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0029_unicode_slugfield_dj19'),
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageTopMenuLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Заголовок')),
                ('caption_en', models.CharField(blank=True, max_length=255, verbose_name='[EN] Заголовок')),
                ('link_external', models.URLField(blank=True, verbose_name='Зовнішнє посилання')),
                ('link_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.Page', verbose_name='Або посилання на існуючу сторінку')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.core.fields.RichTextField(default='', verbose_name='[UA] Загальний текст сторінки'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='body_en',
            field=wagtail.core.fields.RichTextField(default='', verbose_name='[EN] Загальний текст сторінки'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='title_en',
            field=models.CharField(default='', max_length=255, verbose_name='[EN] Назва сторінки'),
        ),
        migrations.AddField(
            model_name='homepagetopmenulink',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_menu_links', to='home.HomePage'),
        ),
    ]
