# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20160922_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='global_class',
            field=models.CharField(default='', max_length=255, verbose_name='CSS-Клас сторінки'),
        ),
    ]
