# Generated by Django 4.1.4 on 2022-12-21 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_staticpage"),
    ]

    operations = [
        migrations.CreateModel(
            name="GenericSiteSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("github", models.URLField()),
                ("telegram", models.URLField()),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=30)),
                ("copyright", models.CharField(max_length=120)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
