# Generated by Django 4.1.4 on 2023-01-04 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_langukmainmenuitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="svg_image",
            field=models.TextField(
                default="",
                help_text="Content of the SVG tag, ignored if empty",
                verbose_name="SVG image icon (raw text) to display next to menu item",
            ),
        ),
        migrations.AddField(
            model_name="staticpage",
            name="svg_image",
            field=models.TextField(
                default="",
                help_text="Content of the SVG tag, ignored if empty",
                verbose_name="SVG image icon (raw text) to display next to menu item",
            ),
        ),
        migrations.AlterField(
            model_name="langukmainmenuitem",
            name="show_in_footer",
            field=models.BooleanField(
                default=True,
                help_text="Display this item in the site footer",
                verbose_name="Show menu item in the footer menu",
            ),
        ),
    ]
