# Generated by Django 4.1.4 on 2023-01-05 16:51

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0010_homepage_svg_image_staticpage_svg_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="slogan_text",
            field=wagtail.fields.RichTextField(
                default="", verbose_name="[UA] Слоган (текст)"
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="slogan_text_en",
            field=wagtail.fields.RichTextField(
                default="", verbose_name="[EN] Слоган (текст)"
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="slogan_title",
            field=models.TextField(default="", verbose_name="[UA] Слоган (заголовок)"),
        ),
        migrations.AddField(
            model_name="homepage",
            name="slogan_title_en",
            field=models.TextField(default="", verbose_name="[EN] Слоган (заголовок)"),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="svg_image",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Content of the SVG tag, ignored if empty",
                verbose_name="SVG image icon (raw text) to display next to menu item",
            ),
        ),
        migrations.AlterField(
            model_name="staticpage",
            name="svg_image",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Content of the SVG tag, ignored if empty",
                verbose_name="SVG image icon (raw text) to display next to menu item",
            ),
        ),
        migrations.DeleteModel(
            name="HomePageTopMenuLink",
        ),
    ]
