# Generated by Django 4.1.4 on 2023-01-05 17:07

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0011_homepage_slogan_text_homepage_slogan_text_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="aboutus_text",
            field=wagtail.fields.RichTextField(
                default="", verbose_name="[UA] Про нас (текст)"
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="aboutus_text_en",
            field=wagtail.fields.RichTextField(
                default="", verbose_name="[EN] Про нас (текст)"
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="aboutus_title",
            field=models.TextField(default="", verbose_name="[UA] Про нас (заголовок)"),
        ),
        migrations.AddField(
            model_name="homepage",
            name="aboutus_title_en",
            field=models.TextField(default="", verbose_name="[EN] Про нас (заголовок)"),
        ),
    ]
