# Generated by Django 4.1.8 on 2023-06-25 12:52

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0013_productpage_productspage"),
    ]

    operations = [
        migrations.AddField(
            model_name="productspage",
            name="intro",
            field=wagtail.fields.RichTextField(
                default="", verbose_name="[UA] Вводний текст"
            ),
        ),
        migrations.AddField(
            model_name="productspage",
            name="intro_en",
            field=wagtail.fields.RichTextField(
                default="", verbose_name="[EN] Вводний текст"
            ),
        ),
    ]
