# Generated by Django 4.1.8 on 2023-06-25 14:12

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("home", "0014_productspage_intro_productspage_intro_en"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartnerLink",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "partner_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Назва партнера"
                    ),
                ),
                (
                    "partner_name_en",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="[EN] Назва партнера"
                    ),
                ),
                (
                    "link_external",
                    models.URLField(blank=True, verbose_name="Посилання на партнера"),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partners",
                        to="home.homepage",
                    ),
                ),
                (
                    "partner_logo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Логотип партнеру",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
