# Generated by Django 4.1.8 on 2023-06-25 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("home", "0015_partnerlink"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="partners_title",
            field=models.TextField(
                default="", verbose_name="[UA] Наші партнери (заголовок)"
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="partners_title_en",
            field=models.TextField(
                default="", verbose_name="[EN] Наші партнери (заголовок)"
            ),
        ),
        migrations.AlterField(
            model_name="partnerlink",
            name="partner_logo",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Логотип партнеру",
            ),
        ),
    ]
