# Generated by Django 4.1.8 on 2023-06-25 15:31

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0016_homepage_partners_title_homepage_partners_title_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="useful_text",
            field=wagtail.fields.RichTextField(
                default="", verbose_name="[UA] Кому це може бути корисно (текст)"
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="useful_text_en",
            field=wagtail.fields.RichTextField(
                default="", verbose_name="[EN] Кому це може бути корисно (текст)"
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="useful_title",
            field=models.TextField(
                default="", verbose_name="[UA] Кому це може бути корисно (заголовок)"
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="useful_title_en",
            field=models.TextField(
                default="", verbose_name="[EN] Кому це може бути корисно (заголовок)"
            ),
        ),
    ]
