# Generated by Django 4.1.8 on 2023-06-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0018_remove_homepage_useful_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="become_a_part_cta",
            field=models.TextField(
                default="", verbose_name="[UA] Стань частиною (заклик)"
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="become_a_part_cta_en",
            field=models.TextField(
                default="", verbose_name="[EN] Стань частиною (заклик)"
            ),
        ),
    ]
