# Generated by Django 4.1.8 on 2023-06-25 17:59

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0020_homepage_media_title_homepage_media_title_en_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="become_a_part_cta",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="become_a_part_cta_en",
        ),
        migrations.RemoveField(
            model_name="pressarticles",
            name="page",
        ),
        migrations.AlterField(
            model_name="homepage",
            name="aboutus_text",
            field=wagtail.fields.RichTextField(
                default="", verbose_name="[UA] Розділ 'Про нас' (текст)"
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="aboutus_text_en",
            field=wagtail.fields.RichTextField(
                default="", verbose_name="[EN] Розділ 'Про нас' (текст)"
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="aboutus_title",
            field=models.TextField(
                default="", verbose_name="[UA] Розділ 'Про нас' (заголовок)"
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="aboutus_title_en",
            field=models.TextField(
                default="", verbose_name="[EN] Розділ 'Про нас' (заголовок)"
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="media_title",
            field=models.TextField(
                default="", verbose_name="[UA] Розділ медіа (заголовок)"
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="media_title_en",
            field=models.TextField(
                default="", verbose_name="[EN] Розділ медіа (заголовок)"
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="partners_title",
            field=models.TextField(
                default="", verbose_name="[UA] Розділ партнерів (заголовок)"
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="partners_title_en",
            field=models.TextField(
                default="", verbose_name="[EN] Розділ партнерів (заголовок)"
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="useful_title",
            field=models.TextField(
                default="", verbose_name="[UA] Розділ користувачів (заголовок)"
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="useful_title_en",
            field=models.TextField(
                default="", verbose_name="[EN] Розділ користувачів (заголовок)"
            ),
        ),
    ]
