# Generated by Django 4.1.8 on 2023-06-25 18:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0021_remove_homepage_become_a_part_cta_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pressarticles",
            options={},
        ),
        migrations.RemoveField(
            model_name="pressarticles",
            name="sort_order",
        ),
    ]
