# Generated by Django 4.1.8 on 2023-07-08 22:37

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0083_workflowcontenttype"),
        ("home", "0025_remove_homepage_media_title_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutUsPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        default="", max_length=255, verbose_name="[EN] Назва сторінки"
                    ),
                ),
                (
                    "global_class",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="CSS-Клас сторінки",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.RichTextField(
                        default="", verbose_name="[UA] Загальний текст сторінки"
                    ),
                ),
                (
                    "body_en",
                    wagtail.fields.RichTextField(
                        default="", verbose_name="[EN] Загальний текст сторінки"
                    ),
                ),
                (
                    "svg_image",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Content of the SVG tag, ignored if empty",
                        verbose_name="SVG image icon (raw text) to display next to menu item",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
