# Generated by Django 4.1.8 on 2024-03-22 13:54

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("home", "0027_aboutuspage_direction1_aboutuspage_direction1_en_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Volunteer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Повне ім'я"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="[EN] Повне ім'я"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Роль або внесок"
                    ),
                ),
                (
                    "role_en",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="[EN] Роль або внесок"
                    ),
                ),
                (
                    "github",
                    models.URLField(blank=True, verbose_name="Профіль у github"),
                ),
                (
                    "telegram",
                    models.URLField(blank=True, verbose_name="Профіль у telegram"),
                ),
                (
                    "facebook",
                    models.URLField(blank=True, verbose_name="Профіль у facebook"),
                ),
                (
                    "instagram",
                    models.URLField(blank=True, verbose_name="Профіль у instagram"),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="volunteers",
                        to="home.aboutuspage",
                    ),
                ),
                (
                    "photo",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Фото користувача",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Founder",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Повне ім'я"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="[EN] Повне ім'я"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Роль або внесок"
                    ),
                ),
                (
                    "role_en",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="[EN] Роль або внесок"
                    ),
                ),
                (
                    "github",
                    models.URLField(blank=True, verbose_name="Профіль у github"),
                ),
                (
                    "telegram",
                    models.URLField(blank=True, verbose_name="Профіль у telegram"),
                ),
                (
                    "facebook",
                    models.URLField(blank=True, verbose_name="Профіль у facebook"),
                ),
                (
                    "instagram",
                    models.URLField(blank=True, verbose_name="Профіль у instagram"),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="founders",
                        to="home.aboutuspage",
                    ),
                ),
                (
                    "photo",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Фото користувача",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
