# Generated by Django 4.1.8 on 2024-03-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0028_volunteer_founder"),
    ]

    operations = [
        migrations.AddField(
            model_name="founder",
            name="google_scholar",
            field=models.URLField(blank=True, verbose_name="Профіль у google scholar"),
        ),
        migrations.AddField(
            model_name="founder",
            name="huggingface",
            field=models.URLField(blank=True, verbose_name="Профіль у huggingface"),
        ),
        migrations.AddField(
            model_name="founder",
            name="linkedin",
            field=models.URLField(blank=True, verbose_name="Профіль у linkedin"),
        ),
        migrations.AddField(
            model_name="volunteer",
            name="google_scholar",
            field=models.URLField(blank=True, verbose_name="Профіль у google scholar"),
        ),
        migrations.AddField(
            model_name="volunteer",
            name="huggingface",
            field=models.URLField(blank=True, verbose_name="Профіль у huggingface"),
        ),
        migrations.AddField(
            model_name="volunteer",
            name="linkedin",
            field=models.URLField(blank=True, verbose_name="Профіль у linkedin"),
        ),
    ]
