# Generated by Django 4.1.8 on 2024-03-23 23:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0029_founder_google_scholar_founder_huggingface_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutuspage",
            name="volunteers_title",
            field=models.TextField(
                default="", verbose_name="[UA] Розділ Наша Команда (заголовок)"
            ),
        ),
        migrations.AddField(
            model_name="aboutuspage",
            name="volunteers_title_en",
            field=models.TextField(
                default="", verbose_name="[EN] Розділ Наша Команда (заголовок)"
            ),
        ),
    ]
