# Generated by Django 4.1.8 on 2024-03-24 00:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0030_aboutuspage_volunteers_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="founder",
            name="twitter",
            field=models.URLField(blank=True, verbose_name="Профіль у twitter/x"),
        ),
        migrations.AddField(
            model_name="volunteer",
            name="twitter",
            field=models.URLField(blank=True, verbose_name="Профіль у twitter/x"),
        ),
    ]
