# Generated by Django 4.1.8 on 2024-03-24 23:28

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0032_manifestopage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutuspage",
            name="body",
            field=wagtail.fields.RichTextField(
                blank=True, default="", verbose_name="[UA] Загальний текст сторінки"
            ),
        ),
        migrations.AlterField(
            model_name="aboutuspage",
            name="body_en",
            field=wagtail.fields.RichTextField(
                blank=True, default="", verbose_name="[EN] Загальний текст сторінки"
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.RichTextField(
                blank=True, default="", verbose_name="[UA] Загальний текст сторінки"
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="body_en",
            field=wagtail.fields.RichTextField(
                blank=True, default="", verbose_name="[EN] Загальний текст сторінки"
            ),
        ),
        migrations.AlterField(
            model_name="manifestopage",
            name="body",
            field=wagtail.fields.RichTextField(
                blank=True, default="", verbose_name="[UA] Загальний текст сторінки"
            ),
        ),
        migrations.AlterField(
            model_name="manifestopage",
            name="body_en",
            field=wagtail.fields.RichTextField(
                blank=True, default="", verbose_name="[EN] Загальний текст сторінки"
            ),
        ),
        migrations.AlterField(
            model_name="manifestopage",
            name="thesis1_description",
            field=wagtail.fields.RichTextField(
                default="", verbose_name="[UA] Теза 1 (опис)"
            ),
        ),
        migrations.AlterField(
            model_name="manifestopage",
            name="thesis1_description_en",
            field=wagtail.fields.RichTextField(
                default="", verbose_name="[EN] Теза 1 (опис)"
            ),
        ),
        migrations.AlterField(
            model_name="productpage",
            name="body",
            field=wagtail.fields.RichTextField(
                blank=True, default="", verbose_name="[UA] Загальний текст сторінки"
            ),
        ),
        migrations.AlterField(
            model_name="productpage",
            name="body_en",
            field=wagtail.fields.RichTextField(
                blank=True, default="", verbose_name="[EN] Загальний текст сторінки"
            ),
        ),
        migrations.AlterField(
            model_name="productspage",
            name="body",
            field=wagtail.fields.RichTextField(
                blank=True, default="", verbose_name="[UA] Загальний текст сторінки"
            ),
        ),
        migrations.AlterField(
            model_name="productspage",
            name="body_en",
            field=wagtail.fields.RichTextField(
                blank=True, default="", verbose_name="[EN] Загальний текст сторінки"
            ),
        ),
        migrations.AlterField(
            model_name="staticpage",
            name="body",
            field=wagtail.fields.RichTextField(
                blank=True, default="", verbose_name="[UA] Загальний текст сторінки"
            ),
        ),
        migrations.AlterField(
            model_name="staticpage",
            name="body_en",
            field=wagtail.fields.RichTextField(
                blank=True, default="", verbose_name="[EN] Загальний текст сторінки"
            ),
        ),
    ]
