# Generated by Django 4.1.8 on 2024-03-25 00:04

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0033_alter_aboutuspage_body_alter_aboutuspage_body_en_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manifestopage",
            name="thesis2_description",
            field=wagtail.fields.RichTextField(
                default="", verbose_name="[UA] Теза 2 (опис)"
            ),
        ),
        migrations.AlterField(
            model_name="manifestopage",
            name="thesis2_description_en",
            field=wagtail.fields.RichTextField(
                default="", verbose_name="[EN] Теза 2 (опис)"
            ),
        ),
        migrations.AlterField(
            model_name="manifestopage",
            name="thesis3_description",
            field=wagtail.fields.RichTextField(
                default="", verbose_name="[UA] Теза 3 (опис)"
            ),
        ),
        migrations.AlterField(
            model_name="manifestopage",
            name="thesis3_description_en",
            field=wagtail.fields.RichTextField(
                default="", verbose_name="[EN] Теза 3 (опис)"
            ),
        ),
    ]
