# Generated by Django 4.2.11 on 2024-03-26 23:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0035_contactuspage"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactUsMessage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст")),
                ("email", models.EmailField(max_length=512, verbose_name="e-mail")),
                (
                    "phone",
                    models.TextField(
                        blank=True, max_length=512, verbose_name="Телефон"
                    ),
                ),
                (
                    "added",
                    models.DateTimeField(auto_now=True, verbose_name="Був надісланий"),
                ),
            ],
            options={
                "verbose_name": "Зворотній зв'язок",
                "verbose_name_plural": "Зворотній зв'язок",
            },
        ),
    ]
