# Generated by Django 4.2.11 on 2024-03-26 23:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0036_contactusmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactusmessage",
            name="author",
            field=models.EmailField(
                default="test", max_length=512, verbose_name="Ім'я"
            ),
            preserve_default=False,
        ),
    ]
