# Generated by Django 4.2.11 on 2024-03-27 14:10

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0037_contactusmessage_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactuspage",
            name="thank_you_caption",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Подяка за повідомлення"
            ),
        ),
        migrations.AddField(
            model_name="contactuspage",
            name="thank_you_caption_en",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="[EN] Подяка за повідомлення"
            ),
        ),
        migrations.AddField(
            model_name="contactuspage",
            name="thank_you_text",
            field=wagtail.fields.RichTextField(
                default="", verbose_name="Текст подяки за повідомлення"
            ),
        ),
        migrations.AddField(
            model_name="contactuspage",
            name="thank_you_text_en",
            field=wagtail.fields.RichTextField(
                default="", verbose_name="[EN] Текст подяки за повідомлення"
            ),
        ),
        migrations.AlterField(
            model_name="contactusmessage",
            name="author",
            field=models.TextField(max_length=512, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name="contactusmessage",
            name="text",
            field=models.TextField(verbose_name="Повідомлення*"),
        ),
    ]
