# Generated by Django 4.2.11 on 2024-03-27 14:16

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0038_contactuspage_thank_you_caption_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactuspage",
            name="thank_you_caption",
            field=wagtail.fields.RichTextField(
                default="", verbose_name="Подяка за повідомлення"
            ),
        ),
        migrations.AlterField(
            model_name="contactuspage",
            name="thank_you_caption_en",
            field=wagtail.fields.RichTextField(
                default="", verbose_name="[EN] Подяка за повідомлення"
            ),
        ),
    ]
