# Generated by Django 4.1.8 on 2026-07-05 07:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0039_alter_contactuspage_thank_you_caption_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutuspage",
            name="title_en",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="[EN] Назва сторінки",
            ),
        ),
        migrations.AlterField(
            model_name="contactuspage",
            name="title_en",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="[EN] Назва сторінки",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="title_en",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="[EN] Назва сторінки",
            ),
        ),
        migrations.AlterField(
            model_name="manifestopage",
            name="title_en",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="[EN] Назва сторінки",
            ),
        ),
        migrations.AlterField(
            model_name="productpage",
            name="title_en",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="[EN] Назва сторінки",
            ),
        ),
        migrations.AlterField(
            model_name="productspage",
            name="title_en",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="[EN] Назва сторінки",
            ),
        ),
        migrations.AlterField(
            model_name="staticpage",
            name="title_en",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="[EN] Назва сторінки",
            ),
        ),
    ]
