# Generated by Django 4.1.8 on 2026-07-05 07:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0040_alter_aboutuspage_title_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="genericsitesettings",
            name="notification_emails",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Email-адреси через кому: сюди надходять повідомлення з форм (зворотній зв'язок, заявки на продукти, відгуки)",
                verbose_name="Сповіщення редакторам",
            ),
        ),
    ]
